REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\cell_info\cell_info.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\cell_info\arm\gccmain.o" -c "C:\Program Files\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\cell_info\include" -I "D:\MyGitHub\cell_info\include\service" -I "D:\MyGitHub\cell_info\include\component" -I "D:\MyGitHub\cell_info\ResID" -I "D:\MyGitHub\cell_info\src\app\widget" -I "D:\MyGitHub\cell_info\src\app\launcher" -I "D:\MyGitHub\cell_info\src\app\wallpaper" -I "D:\MyGitHub\cell_info\src\app\screen_lock" -I "D:\MyGitHub\cell_info\include\service" -I "D:\MyGitHub\cell_info\include\component" -I "D:\MyGitHub\cell_info\include\service" -I "D:\MyGitHub\cell_info\src\framework" -I "D:\MyGitHub\cell_info\src\framework\ui_core\base" -I "D:\MyGitHub\cell_info\src\framework\ui_core\mvc" -I "D:\MyGitHub\cell_info\src\framework\ui_core\pme" -I "D:\MyGitHub\cell_info\src\framework\mmi_core" -I "D:\MyGitHub\cell_info\src\ui_engine\vrt\interface" -I "D:\MyGitHub\cell_info\src\component" -I "D:\MyGitHub\cell_info\src\ui_engine\framework\xml" -I "D:\MyGitHub\cell_info"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\cell_info\arm\cell_info.o" -c "d:\MyGitHub\cell_info\cell_info.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\cell_info\include" -I "D:\MyGitHub\cell_info\include\service" -I "D:\MyGitHub\cell_info\include\component" -I "D:\MyGitHub\cell_info\ResID" -I "D:\MyGitHub\cell_info\src\app\widget" -I "D:\MyGitHub\cell_info\src\app\launcher" -I "D:\MyGitHub\cell_info\src\app\wallpaper" -I "D:\MyGitHub\cell_info\src\app\screen_lock" -I "D:\MyGitHub\cell_info\include\service" -I "D:\MyGitHub\cell_info\include\component" -I "D:\MyGitHub\cell_info\include\service" -I "D:\MyGitHub\cell_info\src\framework" -I "D:\MyGitHub\cell_info\src\framework\ui_core\base" -I "D:\MyGitHub\cell_info\src\framework\ui_core\mvc" -I "D:\MyGitHub\cell_info\src\framework\ui_core\pme" -I "D:\MyGitHub\cell_info\src\framework\mmi_core" -I "D:\MyGitHub\cell_info\src\ui_engine\vrt\interface" -I "D:\MyGitHub\cell_info\src\component" -I "D:\MyGitHub\cell_info\src\ui_engine\framework\xml" -I "D:\MyGitHub\cell_info"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\cell_info\arm\console.o" -c "d:\MyGitHub\cell_info\console.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\cell_info\include" -I "D:\MyGitHub\cell_info\include\service" -I "D:\MyGitHub\cell_info\include\component" -I "D:\MyGitHub\cell_info\ResID" -I "D:\MyGitHub\cell_info\src\app\widget" -I "D:\MyGitHub\cell_info\src\app\launcher" -I "D:\MyGitHub\cell_info\src\app\wallpaper" -I "D:\MyGitHub\cell_info\src\app\screen_lock" -I "D:\MyGitHub\cell_info\include\service" -I "D:\MyGitHub\cell_info\include\component" -I "D:\MyGitHub\cell_info\include\service" -I "D:\MyGitHub\cell_info\src\framework" -I "D:\MyGitHub\cell_info\src\framework\ui_core\base" -I "D:\MyGitHub\cell_info\src\framework\ui_core\mvc" -I "D:\MyGitHub\cell_info\src\framework\ui_core\pme" -I "D:\MyGitHub\cell_info\src\framework\mmi_core" -I "D:\MyGitHub\cell_info\src\ui_engine\vrt\interface" -I "D:\MyGitHub\cell_info\src\component" -I "D:\MyGitHub\cell_info\src\ui_engine\framework\xml" -I "D:\MyGitHub\cell_info"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\cell_info\cell_info.axf"  "D:\MyGitHub\cell_info\arm\gccmain.o"  "D:\MyGitHub\cell_info\arm\cell_info.o"  "D:\MyGitHub\cell_info\arm\console.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE_SDK\lib\MRE30\armgcc\scat.ld" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\percommon.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persim.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persysstorage.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persysfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perlbs.a"
REM Pack resource to app 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\cell_info\cell_info.pkd" -e AXF "D:\MyGitHub\cell_info\cell_info.vcproj" "D:\MyGitHub\cell_info\cell_info.axf"
REM Add tag infromation 
"C:\Program Files\MRE_SDK\tools\PackDigist.exe" "D:\MyGitHub\cell_info\cell_info.vcproj" "cell_info" "0.1.0" "RDZDX" "500" "NotSupportBg" "Not Support rotate" "cell_info" "cell_info" "cell_info" "9123456789123456" "content" " File SIM card SysStorage SysFile LBS" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\cell_info\arm D:\MyGitHub\cell_info\build.log

